services:
  backend:
    build: ./backend
    ports:
      - '5002:5002'
    environment:
      - PORT=5002
      - MONGO_URI=mongodb://mongo:27017/sales_dashboard
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    environment:
      - REACT_APP_API_URL=http://backend:5002/api
    depends_on:
      - backend
  mongo:
    image: mongo
    ports:
      - '27017:27017'